---
name: "NPM Cache Action"
description: "Initialize NPM Cache"
inputs:
  nodeModulesPath:
    description: "Path for node_modules"
    required: false
    default: "**node_modules"
  packageLockPath:
    description: "Path for package-lock.json"
    required: false
    default: "**/package-lock.json"
  nodeVersion:
    description: "Node version"
    required: false
    default: "20"
runs:
  using: "composite"
  steps:
    - name: 🆙 Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.nodeVersion }}
        cache-dependency-path: screen-reader-test/package-lock.json

    - name: Display node and npm version
      shell: bash
      run: |
        node --version
        npm --version

    - name: 🆒 Init Cache
      uses: actions/cache@v4
      id: "cache"
      with:
        path: screen-reader-test/node-modules
        key: ${{ runner.os }}-node-${{ inputs.nodeVersion }}-${{ hashFiles(inputs.packageLockPath) }}
        restore-keys: |
          ${{ runner.os }}-node-${{ inputs.nodeVersion }}

    - name: ⏬ NPM ci
      shell: bash
      working-directory: screen-reader-test
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        npm ci
        ls screen-reader-test/node-modules
