name: Init Workflow

on:
  workflow_call:

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: ⏬ Checkout repo
        uses: actions/checkout@v4

      - name: 🔄 Init Cache Default
        uses: ./.github/actions/npm-cache
