---
name: Default Pipeline

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  init-playwright:
    uses: ./.github/workflows/00-init-playwright.yml

  test-screen-reader:
    uses: ./.github/workflows/02-e2e-screen-reader.yml
    needs: [init-playwright]

